/**
 * Workbench handler integration tests
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { EventEmitter } from 'events'
import type { IpcMainInvokeEvent } from 'electron'

// Mock SDK response (can be controlled per test)
let mockSdkResponse: string | Error = 'Placeholder response'

// Mock the Agent SDK
vi.mock('@anthropic-ai/claude-agent-sdk', () => ({
  query: vi.fn(() => {
    const generator = (async function* () {
      if (mockSdkResponse instanceof Error) {
        throw mockSdkResponse
      }
      yield {
        type: 'assistant',
        message: {
          content: [{ type: 'text', text: mockSdkResponse }]
        }
      }
    })()

    return {
      [Symbol.asyncIterator]() {
        return generator
      },
      return: () => generator.return()
    }
  })
}))

// Mock dependencies
vi.mock('../../auth-guard', () => ({
  checkAuthStatus: vi.fn().mockResolvedValue({
    cliFound: true,
    tokenFound: true,
    tokenExpired: false,
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 7 days from now
  })
}))

vi.mock('../../git', () => ({
  getRepoPaths: vi.fn().mockReturnValue({
    BDE: '/Users/test/projects/BDE',
    TestRepo: '/Users/test/projects/TestRepo'
  })
}))

vi.mock('../../env-utils', () => ({
  buildAgentEnv: () => ({ ...process.env }),
  buildAgentEnvWithAuth: () => ({ ...process.env })
}))

/** Helper: create a fake spawn child that writes `output` to stdout and exits 0. */
function _createFakeSpawnChild(output: string) {
  const child = new EventEmitter() as any
  child.stdout = new EventEmitter()
  child.stderr = new EventEmitter()
  child.stdin = { write: vi.fn(), end: vi.fn() }
  child.kill = vi.fn()

  // Emit data + close on next tick so the caller has time to attach listeners
  process.nextTick(() => {
    child.stdout.emit('data', Buffer.from(output))
    child.emit('close', 0)
  })
  return child
}

vi.mock('child_process', () => ({
  execFile: vi.fn((cmd: string, args: string[], _opts: unknown, cb: Function) => {
    // Mock git status - clean repo
    if (cmd === 'git' && args[0] === 'status') {
      cb(null, { stdout: '', stderr: '' })
    }
    // Mock grep - no results
    else if (cmd === 'grep') {
      const err: any = new Error('No matches')
      err.code = 1
      cb(err)
    }
    // Default: call back with empty result
    else {
      cb(null, { stdout: '', stderr: '' })
    }
  }),
  spawn: vi.fn((_cmd: string, _args: string[], _opts: unknown) => {
    // The actual prompt content is piped via stdin, so we capture it via stdin.write
    // and return a response based on it. We defer this by capturing the child and
    // using stdin.end to trigger the response.
    const child = new EventEmitter() as any
    child.stdout = new EventEmitter()
    child.stderr = new EventEmitter()
    child.kill = vi.fn()

    let writtenData = ''
    child.stdin = {
      write: vi.fn((data: string) => {
        writtenData += data
      }),
      end: vi.fn(() => {
        // Determine response based on the prompt that was piped in
        let output: string
        if (writtenData.includes('reviewing a coding agent spec')) {
          output = JSON.stringify({
            clarity: { status: 'warn', message: 'Placeholder clarity check' },
            scope: { status: 'warn', message: 'Placeholder scope check' },
            filesExist: { status: 'warn', message: 'Placeholder files check' }
          })
        } else if (
          writtenData.includes('writing a coding agent spec') ||
          writtenData.includes('Generate a')
        ) {
          output = `# Test Task\n\nPlaceholder spec generated by AI.`
        } else {
          output = `Placeholder response about "Test Task".`
        }
        process.nextTick(() => {
          child.stdout.emit('data', Buffer.from(output))
          child.emit('close', 0)
        })
      })
    }
    return child
  })
}))

vi.mock('../../ipc-utils', () => ({
  safeHandle: vi.fn()
}))

const mockAgentManager = {
  getStatus: vi.fn().mockReturnValue({
    running: true,
    concurrency: { maxSlots: 2, activeCount: 0 },
    activeAgents: []
  })
} as any

// Import handlers after mocks are set up
import { registerWorkbenchHandlers } from '../workbench'
import { safeHandle } from '../../ipc-utils'

describe('Workbench handlers', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockSdkResponse = 'Placeholder response'
  })

  it('registers all 7 workbench handlers', () => {
    registerWorkbenchHandlers(mockAgentManager)

    expect(safeHandle).toHaveBeenCalledTimes(7)
    expect(safeHandle).toHaveBeenCalledWith('workbench:checkOperational', expect.any(Function))
    expect(safeHandle).toHaveBeenCalledWith('workbench:researchRepo', expect.any(Function))
    expect(safeHandle).toHaveBeenCalledWith('workbench:chat', expect.any(Function))
    expect(safeHandle).toHaveBeenCalledWith('workbench:chatStream', expect.any(Function))
    expect(safeHandle).toHaveBeenCalledWith('workbench:cancelStream', expect.any(Function))
    expect(safeHandle).toHaveBeenCalledWith('workbench:generateSpec', expect.any(Function))
    expect(safeHandle).toHaveBeenCalledWith('workbench:checkSpec', expect.any(Function))
  })

  it('checkOperational handler returns all expected fields', async () => {
    let checkOperationalHandler: any

    vi.mocked(safeHandle).mockImplementation((channel, handler) => {
      if (channel === 'workbench:checkOperational') {
        checkOperationalHandler = handler
      }
    })

    registerWorkbenchHandlers(mockAgentManager)

    expect(checkOperationalHandler).toBeDefined()

    const mockEvent = {} as IpcMainInvokeEvent
    const result = await checkOperationalHandler(mockEvent, { repo: 'BDE' })

    expect(result).toHaveProperty('auth')
    expect(result).toHaveProperty('repoPath')
    expect(result).toHaveProperty('gitClean')
    expect(result).toHaveProperty('noConflict')
    expect(result).toHaveProperty('slotsAvailable')

    expect(result.auth.status).toBe('pass')
    expect(result.repoPath.status).toBe('pass')
    expect(result.repoPath.path).toBe('/Users/test/projects/BDE')
  })

  it('researchRepo handler returns expected structure', async () => {
    let researchRepoHandler: any

    vi.mocked(safeHandle).mockImplementation((channel, handler) => {
      if (channel === 'workbench:researchRepo') {
        researchRepoHandler = handler
      }
    })

    registerWorkbenchHandlers(mockAgentManager)

    expect(researchRepoHandler).toBeDefined()

    const mockEvent = {} as IpcMainInvokeEvent
    const result = await researchRepoHandler(mockEvent, { query: 'test', repo: 'BDE' })

    expect(result).toHaveProperty('content')
    expect(result).toHaveProperty('filesSearched')
    expect(result).toHaveProperty('totalMatches')
    expect(Array.isArray(result.filesSearched)).toBe(true)
  })

  it('chat stub returns placeholder', async () => {
    let chatHandler: any

    vi.mocked(safeHandle).mockImplementation((channel, handler) => {
      if (channel === 'workbench:chat') {
        chatHandler = handler
      }
    })

    registerWorkbenchHandlers(mockAgentManager)

    // Set SDK response for chat
    mockSdkResponse = 'Placeholder response about "Test Task".'

    const mockEvent = {} as IpcMainInvokeEvent
    const result = await chatHandler(mockEvent, {
      messages: [{ role: 'user', content: 'test' }],
      formContext: { title: 'Test Task', repo: 'BDE', spec: 'test spec' }
    })

    expect(result.content).toContain('Placeholder')
    expect(result.content).toContain('Test Task')
  })

  it('generateSpec stub returns placeholder', async () => {
    let generateSpecHandler: any

    vi.mocked(safeHandle).mockImplementation((channel, handler) => {
      if (channel === 'workbench:generateSpec') {
        generateSpecHandler = handler
      }
    })

    registerWorkbenchHandlers(mockAgentManager)

    // Set SDK response for spec generation
    mockSdkResponse = '# Test Task\n\nPlaceholder spec generated by AI.'

    const mockEvent = {} as IpcMainInvokeEvent
    const result = await generateSpecHandler(mockEvent, {
      title: 'Test Task',
      repo: 'BDE',
      templateHint: 'bugfix'
    })

    expect(result.spec).toContain('Test Task')
    expect(result.spec).toContain('Placeholder')
  })

  it('checkSpec stub returns all expected fields', async () => {
    let checkSpecHandler: any

    vi.mocked(safeHandle).mockImplementation((channel, handler) => {
      if (channel === 'workbench:checkSpec') {
        checkSpecHandler = handler
      }
    })

    registerWorkbenchHandlers(mockAgentManager)

    // Set SDK response for spec checking
    mockSdkResponse = JSON.stringify({
      clarity: { status: 'warn', message: 'Placeholder clarity check' },
      scope: { status: 'warn', message: 'Placeholder scope check' },
      filesExist: { status: 'warn', message: 'Placeholder files check' }
    })

    const mockEvent = {} as IpcMainInvokeEvent
    const result = await checkSpecHandler(mockEvent, {
      title: 'Test Task',
      repo: 'BDE',
      spec: 'test spec content'
    })

    expect(result).toHaveProperty('clarity')
    expect(result).toHaveProperty('scope')
    expect(result).toHaveProperty('filesExist')
    expect(result.clarity.status).toBe('warn')
    expect(result.scope.status).toBe('warn')
    expect(result.filesExist.status).toBe('warn')
  })
})
